### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by masudr4n4** [hideakitai/ArtNet#1]
HI @hideakitai 
I am a designer , i want to contribute in this project by providing a design.I just need a permission to make a logo for this projects,if you have any requirments then let me know.
thanks

**Comment by hideakitai** [comment]
@masudr4n4 So sorry for the late reply... but thanks for your proposal! I don't need it currently, thanks!

**Comment by masudr4n4** [comment]
Haha.its ok
