### ISSUE TITLE
Send & Receive not working

### ISSUE THREAD

**Issue by silentonset** [hideakitai/ArtNet#11]
Hi hideakitai,

I've been doing some test with the send_receive and it doesn't seem to be working as expected.

When i use Receive Sketch:
I get :
artnet data (universe : 1) = 
215,149,62,159,64,0,0,0,0,0,0,0,0,0,0... etc_

But when i use send_receive
i get :
_set subscriber
start_

It doesn't seem to execute the function, is the implementation different from the Receive sketch?

**Comment by hideakitai** [comment]
Hi, send_receive's receiver is completely same as receiver example. Can you check ping command from your pc to your device first, and then please check the universe setting.

If everything is fine, let me know your IDE version, board name, board version, ArtNet library version, and sketch if you can.

**Comment by silentonset** [comment]
Hi hideakitai,

All my setting are exactly the same. in fact when i trigger artnet channel 1 @ universe 1.

the serial monitor respond with "set subscriber start" everytime i trigger it

<img width="843" alt="Screenshot 2020-11-10 at 1 06 33 AM" src="https://user-images.githubusercontent.com/33739268/98572795-fd2cd000-22f0-11eb-8d13-049779959bd5.png">


i am using an UNO R3 Board (BN: Arduino Uno VID: 2341PID: 0043 )
with a Hanrun HR911105A (19/06) ethershield (W5100).
i am using Arduino 1.8.13 of the IDE and the latest Artnet Library  v0.1.10

When i compile, i have an error that says "Not enough memory" so i edit the sketch 
"const uint16_t size = 512;" to "const uint16_t size = 10;"

this is the log i get :

Sketch uses 13532 bytes (41%) of program storage space. Maximum is 32256 bytes.
Global variables use 1745 bytes (85%) of dynamic memory, leaving 303 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.
Invalid library found in /Users/mbpr-2013/Documents/Arduino/libraries/hardware: no headers files (.h) found in /Users/mbpr-2013/Documents/Arduino/libraries/hardware
Invalid library found in /Users/mbpr-2013/Documents/Arduino/libraries/DMX_Shield: no headers files (.h) found in /Users/mbpr-2013/Documents/Arduino/libraries/DMX_Shield

**Comment by hideakitai** [comment]
@silentonset Integrated sender/receiver is not available on Arduino UNO. Because it doesn't have enough memory, it hangs when both sender and receiver instance are used as noted in README.

> Some boards without enough memory may not be able to use integrated sender/receiver. Please use only sender OR receiver.

Please consider to use more powerful boards or just use one of sender or receiver. I don't think we're going to use both of them in the same board very often.

**Comment by hideakitai** [comment]
If you have any other question, let me know and reopen issue. Thanks.

**Comment by silentonset** [comment]
Will do, i am trying to get a new board. Will revert once i test on the new board.

**Comment by hideakitai** [comment]
Ok, I hope you can make it!

**Comment by silentonset** [comment]
Do you have any recommended boards?

**Comment by hideakitai** [comment]
It's depending on the situation. What kind of functions do you need? Sending artnet, receiving artnet and what else?

**Comment by silentonset** [comment]
I am hoping to add a dmx shield as well, i am looking to build a dmx/artnet/sACN e131 receiver to trigger a few contact relay and also have to detect button trigger to trigger artnet/dmx/sACN e131.

**Comment by hideakitai** [comment]
To use shields for Uno, Arduino Mega is reasonable and more powerful than Uno. Good luck.

**Comment by silentonset** [comment]
Thanks!

**Comment by silentonset** [comment]
Hi hideaki, i bought an arduino due and it works great!!! Thanks!

**Comment by hideakitai** [comment]
Great to fear that! Hope you can make it :-)
