### ISSUE TITLE
Set poll reply components individually

### ISSUE THREAD

**Issue by thirstyice** [hideakitai/ArtNet#114]
Sometimes I don't want to set the whole `ArtPollReplyConfig` at once. Sometimes I just want to update one value.

I see three ways to implement this:

1. Let the user use their own `ArtNetPollReplyConfig`, which the receiver references through a pointer (#115 
2. Expose `art_net_poll_reply_config` to the user (#116)
3. Provide functions to set each component individually (#117)

**Comment by hideakitai** [comment]
Thanks, I prefer 3rd option

**Comment by hideakitai** [comment]
3rd option was merged
