### ISSUE TITLE
ESP32 Without ethernet

### ISSUE THREAD

**Issue by topjor** [hideakitai/ArtNet#21]
I am currently using a lolin d32 ESP32 board with just wifi, but I keep getting the error that it can't find `Ethernet.h`
I am already using the deep mode for the library resolving (ldf mode)
I also have an ESP8266 but that is not giving any errors, so I may be missing a library (or the library finder) or there is a platform/board support issue.
There is also no way that I see to disable ethernet or wifi currently, if enabled, there is no way to disable.

**Comment by hideakitai** [comment]
@topjor Supported in v0.2.8. Please confirm if it works!

**Comment by topjor** [comment]
I can confirm this works fine. Thank you.

(tried to check yesterday but PIO's caching system would not allow me to update sooner)
