### ISSUE TITLE
Documentation concerning sending Artnet packets

### ISSUE THREAD

**Issue by C0pernic** [hideakitai/ArtNet#23]
Hi there !

I use the Artnet library for teensy 4.1 but I got stuck with sending packets to a Artnet device. Is there any function to format Artnet messages ? 

Basically, I need to send DMX datas through Artnet but I don't get how to format header and stuff in the library.

Thanks in advance,

**Comment by hideakitai** [comment]
Hi, you can find how to stream packets in examples https://github.com/hideakitai/ArtNet/blob/master/examples/Ethernet/sender/sender.ino

Or you can send a packet once as follows as shown in README.

```
artnet.send("127.0.0.1", universe15bit, data_ptr, size); // one-line send
```

Header bytes are automatically added to DMX data.

**Comment by hideakitai** [comment]
@C0pernic If you still have the problem, please reopen the issue.
