### ISSUE TITLE
Callback not executed when adding FastLED

### ISSUE THREAD

**Issue by Jack079** [hideakitai/ArtNet#29]
**Update: 25-12**

I started over to find out where it stops working.
First example file I used is the Ethernet receiver file.
I changed the IP settings and set Universe1 = 0
In the serial monitor I can see that all the 512 channels are changing to the right value.

Second example file I used is the Ethernet receive_fastled file.
I changed the IP settings and set Universe = 0

The FastLED library normaly use _#difine DATA_PIN_6_
_#define_ is not working, it must be **_const uint8_t** to work with this library.

In my first post the number of leds was set to 61.
Now I started with setting the number of leds to 1.
When I use _artnet.forwart_ it works.
But when I set the number of leds to 61, it stopt working
The maximum number of leds I was able set was 14.

I switched form _artnet.forward_ to _artnet.subscribe_
This gives me a error, _Error compiling for board Arduino Nano_
I did change _[&](uint8_t* data, uint16_t size)   _   in _[&](**const** uint8_t* data, **const** uint16_t size)_
Now the error is gone and it works.

In this case the maximum number of leds I was able to set was 2.

now i did add the the serial print part from the ethernet receiver file to see data on the serial monitor.
When the number off leds is bigger than 2, the serial monitor stopt printing so it looks like the callback is not executed any more.

Hope someone can tell me what goes wrong or this can be fixed

Greets Jack

_________________________________________________________________________________________________________________________________
Hi, 

I have a little issue. I don't know if I do something wrong, try something that is not possible, or if it is a real issue. Hope someone can help me out or fix this.

I try to control my LEDs over artnet, but I don't want to contol single LEDs 1 on 1 like in the example file.
-Artnet over Ethernet working.
-FastLED working.
When I try to combine them and add FastLED to a working Artnet script, callback is not executed anymore.

I start at the top step by step.
 -include FastLED.h, 
 -define DATA_PIN and NUM_LEDS
 -define the array of leds
after every step the script is still working.

When I add   FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);   to the setup, 
the callback is not executed anymore.
I have data 0 thru 3 printed out on the serial monitor to check this.

Greets,
Jack

**Comment by hideakitai** [comment]
@Jack079 Sorry for the late reply. It seems to be a problem of shortage of memory of your board, and both Artnet and FastLED require a lot of memory. So I recommend using a more powerful board like Arduino Mega, ESP32, etc. If you still have a problem with a more powerful one, feel free to reopen this issue. Good luck!
