### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by Cubyte** [hideakitai/ArtNet#3]
Not sure but i get this error when i compiled the example
'ArtnetReceiver' does not name a type
what am i doing wrong

**Comment by hideakitai** [comment]
Sorry for late reply, which Arduino board do you use?

**Comment by hideakitai** [comment]
@Cubyte I've supported more boards on v0.1.1, check it out please!

**Comment by hideakitai** [comment]
@conraddang Hi, maybe your ide configuration is not working. First, please use library manager if you are not familiar with Arduino. If you still have the problem, please open a new issue with the following information.

- IDE (Arduino IDE, PlatformIO, etc.) : Arduino IDE ?
- Board/MCU: ESP32-WROOM32 ?
- Board Firmware Version: v2.0.2 ?
- Library Version: ArtNet v0.2.12 ?
- Reproducable & Minimal & Compilable Code
- Additional Information (System chart, etc.)

**Comment by conraddang** [comment]
Hi, thanks a lot! I really appreciate your help. I will try that out. If I still encounter the problem afterwards, i will open a new issue with the details that you need.
