### ISSUE TITLE
Can't make example file run

### ISSUE THREAD

**Issue by conraddang** [hideakitai/ArtNet#35]
Hi hideakitai!

I already posted a question regarding this issue in a closed issue and am now opening this new issue since that's what you told me to do. Firstl of all, here is my setup:

IDE (Arduino IDE, PlatformIO, etc.) : PlatformIO - Core: 5.2.5; Home: 3.4.1
Board/MCU: ESP32-WROOM32 
Board Firmware Version: not sure
Library Version: ArtNet v0.2.12 

I was trying out the Artnet Receiver + FastLED example on ArduinoIDE which did not work and it always returned the error " 'ArtnetReceiver' does not name a type ". After that I tried to add the library using the Arduino library manager, which you suggested, but it still did not work.

Because of that i now moved to the PlatformIO, also because it is nicer to work on. I tried the receive_fastled example file on PlatformIO this time and compilation was successful with the #include <ArtnetWifi.h>. But i can't receive any artnet data. Therefore i wanted to try #include <Artnet.h> instead, since my board is only Wifi compatible. But now it spits out an include error. What am I doing wrong?

Thanks in advance!

**Comment by hideakitai** [comment]
Maybe your network setting is wrong. Please try pinging your device first. After that, confirm the configuration of your Artnet controller.

If you still have a problem, please reopen this issue.
