### ISSUE TITLE
can't find a way to set certain dmx channels

### ISSUE THREAD

**Issue by jasuper** [hideakitai/ArtNet#39]
I can't find a way to set certain values on channels. For example to set on DMX universe 5 the channel 488 on 255 and to change on universe 7 the channel 12 to value 128.

tried to do so with 
artnet.send("2.0.0.7", net, subnet, univ, ch, dmx_value);

so i have put everywhere values, but there is no change of values detected on the ArtNet networlk. 
Also i could ping the network shield of the arduino correctly.

So it could not be an issue, but a lack of knowledge from my side.

best regards.
jasper

**Comment by hideakitai** [comment]
You can do that by changing the corresponding index of the data array.

If you prepare a data array with 512 bytes, you can change channel 488 by changing index 487.

```
uint8_t data[512]; // will be mapped to ch1-512
```

```
data[487] = 255; // ch488 is now 255
```
