### ISSUE TITLE
Arduino DUE

### ISSUE THREAD

**Issue by CurtLemon** [hideakitai/ArtNet#4]
Is it possible to use this library with the ARM chip on the Arduino Due?

**Comment by hideakitai** [comment]
@CurtLemon Sorry for the late reply, currently no. But I will try it in a few days!

**Comment by hideakitai** [comment]
@CurtLemon Supported on v0.1.1. If you have any problem, please feel free to let me know!

**Comment by CurtLemon** [comment]
Thank you so much!  Works great, this is the only library I’ve found that can both send and receive Artnet, and handle it in a clean way. I really appreciate your making this library available and getting back to me so quickly. Thanks Tim Boland From: Hideaki TaiSent: Saturday, June 27, 2020 3:23 AMTo: hideakitai/ArtNetCc: CurtLemon; MentionSubject: Re: [hideakitai/ArtNet] Arduino DUE (#4) Closed #4.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
