### ISSUE TITLE
 How to connect a W5500 shield on esp32 to run the example

### ISSUE THREAD

**Issue by GabrielDSan** [hideakitai/ArtNet#40]
I'm using an esp32 with an etherner shield W5500, do you think it's possible to make it work? because I couldn't find any place to configure the module pins

**Comment by SergDfv** [comment]
> 

Yes, it is possible. The pins are configured in the [Ethernet library](http://www.arduino.cc/en/Reference/Ethernet). By default, the VSPI pins are: SS - 5, SCLK - 18, MISO - 19, MOSI - 23.

**Comment by hideakitai** [comment]
Close this issue, thanks @SergDfv
