### ISSUE TITLE
ESP32-Ethernet-Kit V1.2 does not work

### ISSUE THREAD

**Issue by FHanus** [hideakitai/ArtNet#41]
Hi,

I have the [ESP32-Ethernet-Kit V1.2](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-ethernet-kit.html) board and am trying to set it up with this library. I am using the unchanged "receiver" code. It is plugged to my laptop using the micro-usb and the LAN cable as well. The code compiles and runs, but I am unable to detect it using CMD, nor Art-Net software. 

I suspect this could be due to some incorrect hard-coded pin name in the library or the Ethernet library, but I am unsure how exactly would I find out. Could it perhaps be something simpler that has an easy solution? 

Thanks for any tips!

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/ArtNet/pull/48
