### ISSUE TITLE
Add support for Teensy 4.1 NativeEthernet

### ISSUE THREAD

**Issue by hideakitai** [hideakitai/ArtNet#49]
Ref

- https://github.com/hideakitai/ArduinoOSC/pull/35

**Comment by hideakitai** [comment]
Fixed https://github.com/hideakitai/ArtNet/pull/51

**Comment by callmenick** [comment]
@hideakitai now that this is in, wondering if you can publish a new release so that we can update the libraries from the arduino library manager. Thank you!

**Comment by hideakitai** [comment]
Yes, I will, if I have enough time...
