### ISSUE TITLE
Receiver unsubscribe function

### ISSUE THREAD

**Issue by topjor** [hideakitai/ArtNet#5]
I would like to have a function to cancel / remove / unsubscribe callback functions, in my case for a given universe.

I will be looking into making a PR myself but that probably will be somewhere this or next week.

**Comment by hideakitai** [comment]
Hi, thanks.
I also try to add them if I have time :)

**Comment by hideakitai** [comment]
May be it works, if you have a problem, let me know and reopen this issue. Thanks!

**Comment by topjor** [comment]
Thank you,
I would suggest to unsubscribe from all callbacks when no universe is given as someone might be subscribed to a specific universe or multiple and wants to clear all.

**Comment by hideakitai** [comment]
`subscribe(func)` and `unsubscribe()` is for the callback of every packet in every universe, so I added `clear_subscribers()` to unsubscribe all callbacks.
