### ISSUE TITLE
To many leds to forward FastLed Artnet

### ISSUE THREAD

**Issue by GGabi0101** [hideakitai/ArtNet#57]
Hi i am trying to use your lib with the given fastLed example on a ESP8266 over wifi. I only changed the ssid and pw to match my network. I am sending with my software for only 1 Led like in your example but getting following error:

`
ERROR: Too many LEDs to forward

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (29):
epc1=0x40201054 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffdb0 end: 3fffffc0 offset: 0190
3fffff40:  40202070 3ffee5de 3ffefb2c 40201040  
3fffff50:  00000212 3fff02ac 3ffee5c8 40201b6f  
3fffff60:  40205cd0 18b2a8c0 00000000 00000001  
3fffff70:  3ffefcc4 00ffffff 40205cd0 01b2a8c0  
3fffff80:  00000000 00000000 00000001 3ffee944  
3fffff90:  3fffdad0 00000000 3ffee904 40201c04  
3fffffa0:  3fffdad0 00000000 3ffee904 40203d30  
3fffffb0:  feefeffe feefeffe 3ffe84f0 40100dd9  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
`

ERROR: Too many LEDs to forward. what does this error mean? I have set the same amount of leds for fastled. 
I even tried to set FastLeds LED_NUM higher than from my light program but it had no effect.

if you need more information, i will be happy to give it to you.

Thanks for your help!
Best regargs 
GG

**Comment by hideakitai** [comment]
This is because the received artnet packet size is less than the requested number of LEDs to forward (1 LED requires 3 bytes). #58 fixed it. Please check if it works and reopen if you still need help.
