### ISSUE TITLE
configuring a setup with more than 4 universes 

### ISSUE THREAD

**Issue by cyberboy666** [hideakitai/ArtNet#59]
im wanting to control an installation of probably 1000 leds or more. for this will need to be listening across more than 4 universes - i came up first against the limit of 4 callbacks - wondering why this limit is here? 

is there a better way than using callbacks to subscribe to this many universes ?

(i tried bypassing this in the code and it still compiled and uploaded but im guessing theres a reason not to do it like this lol)

**Comment by hideakitai** [comment]
The limitation of the number of callbacks is based on the PollReply packet. PortTypes, GoodInput/Output, SwIn, etc., are limited to 4 ports. But it is better to subscribe to more than four callbacks and make public 4 of them. So, I will remove the limitation of callbacks. :)

**Comment by hideakitai** [comment]
@cyberboy666 Fixed. Please check it out

**Comment by cyberboy666** [comment]
thank you very much for quick response and updates :heart: :heart:
