### ISSUE TITLE
example that does a PRACTICAL thing like switching on / off an LED 

### ISSUE THREAD

**Issue by StefanL38** [hideakitai/ArtNet#63]
Hello,

it might well be that your library is very versatile and can do a lot of things.
Though I do not understand how.

I have found zero links and zero information about what ArtNet is.
The examples have a subfolder called TouchDesigner  artnet_test.toe

I clicked on artnet_test.toe  and got an empty screen displayed
No idea what this is. 

How about an examples that does a very simple thing in a very practical way like blinking an LED?

If you are still engaged in this project of your artnet-library I would appreciate very much if you add some links on the libraries main-page that link to where a basic explanation about what ArtNet is and how Artnet works can be found.

best regards Stefan

**Comment by hideakitai** [comment]
Fixed. Also, you can find references in [README](https://github.com/hideakitai/ArtNet#reference)
