### ISSUE TITLE
example of how to parse incoming artnet data

### ISSUE THREAD

**Issue by kazimier** [hideakitai/ArtNet#65]
hello 

I recently came across this project - looks incredibly well put together and maintained! thank you.. 

I am just struggling with the receiver example - it all makes sense except for the following ; 

```
void loop() {
    artnet.parse();  // check if artnet packet has come and execute callback
}
```

Do you have any further examples of how I could for example use incoming artnet data to control a PWM value of a pin etc? I am just not totally clear how to strip that info out of the incoming data and translate accordingly.. apologies for the noob nature of the question.

**Comment by hideakitai** [comment]
Hi. If you got artnet packet, callbacks are called automatically. You can handle the packet inside of your callback.

```cpp
    artnet.subscribe(universe, [&](const uint8_t* data, const uint16_t size) {
        // if Artnet packet comes to this universe, this function is called
        for (size_t i = 0; i < size; i++) {
            Serial.println(data[i]);
        } 
    });
```

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue
