### ISSUE TITLE
Un-begin

### ISSUE THREAD

**Issue by thirstyice** [hideakitai/ArtNet#70]
Is there a way to stop art-net after calling `begin()`?
I'm building a device that can output either artnet or sACN, and I want to stop one when using the other.

**Comment by hideakitai** [comment]
Hi, what is the correct meaning of "stop"? If you don't want to send a packet, you can dwithoutt by calling `send()` or `streaming()`.

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
