### ISSUE TITLE
Difference between unsubscribe() and clear_subscribers()?`

### ISSUE THREAD

**Issue by thirstyice** [hideakitai/ArtNet#84]
For the `ArtnetReceiver` API, what is the difference between `unsubscribe()` (with no arguments) and `clear_subscribers()`?

**Comment by hideakitai** [comment]
As you can see in the implementation, 

- `unsucscribe()` (with no arguments) : removes callback that are called whenever packets received
- `clear_subscribers()` : equivalent to call `unsubscribe(universe)` for all universes and `unsubscribe(void)`

https://github.com/hideakitai/ArtNet/blob/41ee72559ed9516ea26b3f486eafb6629ee96de0/Artnet/Receiver.h#L182-L193

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
