### ISSUE TITLE
What is the 'net' variable?

### ISSUE THREAD

**Issue by Shadow1356** [hideakitai/ArtNet#9]
Some of the functions take the argument 'net': 
`artnet.subscribe(net, subnet, universe, function);`

I'm familiar with what is meant by subnet, universe and function in the context of artnet, but what is 'net'? An IP address? Something else?

**Comment by hideakitai** [comment]
Hi, it is the 8-14bits of 15bit universe. I'm following this spec. https://artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf

**Comment by hideakitai** [comment]
@Shadow1356 I've added the reference pages to readme. If you have any other questions, let me know.
