### ISSUE TITLE
Mistype at Receiver.h

### ISSUE THREAD

**Issue by linxlabs** [hideakitai/ArtNet#94]
>  Artnet/Receiver.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Artnet/Receiver.h b/Artnet/Receiver.h
index abd5b25..a086387 100644
--- a/Artnet/Receiver.h
+++ b/Artnet/Receiver.h
@@ -188,7 +188,7 @@ public:
     {
         auto it = this->callback_art_dmx_universes.find(universe);
         if (it != this->callback_art_dmx_universes.end()) {
-            this->callbacks.erase(it);
+            this->callback_art_dmx_universes.erase(it);
         }
     }
     void unsubscribeArtDmxUniverses()

**Comment by hideakitai** [comment]
Thanks for reporting!

**Comment by hideakitai** [comment]
Please try v0.4.4
