### ISSUE TITLE
Wrong PollReply

### ISSUE THREAD

**Issue by linxlabs** [hideakitai/ArtNet#96]
Receiver universes shows in DMX Workshop as DMX Inputs, but must be an DMX Output

**Comment by hideakitai** [comment]
Thanks, how about v0.3.0? Can you make a pull request?

**Comment by hideakitai** [comment]
Also, I think this is correct, but is it not?

> Receiver universes shows in DMX Workshop as DMX Inputs

**Comment by linxlabs** [comment]
Can't check it on 0.3.0.

Receiver code get data from ArtNet and puts it outward. This is an output.
Don't checked this on the sender side yet. Your Sender code gets data from somewhere and puts it to ArtNet. This is an input.

**Comment by hideakitai** [comment]
> Can't check it on 0.3.0.

？

> Receiver code get data from ArtNet and puts it outward. This is an output. Don't checked this on the sender side yet. 

No. Receiver does not output dmx data.

> Your Sender code gets data from somewhere and puts it to ArtNet. This is an input.

No. Sender does not received data.

**Comment by linxlabs** [comment]
Maybe i'm wrong, but look at your fastled example.

It take data from artnet and put it to leds. In terms of artnet it is an output.

**Comment by hideakitai** [comment]
> It take data from artnet and put it to leds. In terms of artnet it is an output.

Receiver receives dmx data via artnet. LEDs are outside of artnet. So it's input.

> Seems that sender don't handle ArtPoll at all

Yes. Sender does not receive artnet packet. Just send artdmx data. So it's output.

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
