### ISSUE TITLE
ArtPoolReply

### ISSUE THREAD

**Issue by alexbst** [hideakitai/ArtNet#97]
ArtPollReplay return wrong universes numbers.

I use subscribeArtDmxUniverse and subscribe 2 universes no matter what universes subscribe to receive ArtPollReplay return 2 times 1 
Before i use 0.3.0 and it work

**Comment by hideakitai** [comment]
ArtPollReply will be sent once per one subscribed universe now. See below

https://github.com/hideakitai/ArtNet/issues/81

**Comment by alexbst** [comment]
Yes
But i subscribe universes 2 and 3 , it 2 times return 1 .

**Comment by hideakitai** [comment]
Could you give me reproducible, compilable, and minimum code?

**Comment by hideakitai** [comment]
I've tested v0.4.4 https://github.com/hideakitai/ArtNet/blob/main/examples/WiFi/receiver/receiver.ino 

This example correctly sent universes 1 and 2. Also, changing universes to 2 and 3 correctly sends 2 and 3.

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
